name: Test Grasshopper Plugin

on: [push, pull_request, release]

jobs:

  build:
    name: "Unit tests"
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Tests_Name: GrasshopperBootstrap.Tests   # Replace with your test project name, i.e. MyWpfApp

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Add NuGet to the PATH: https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Restore the tests
    - name: Restore main project
      run: msbuild GrasshopperBootstrap /t:Restore /p:Configuration="Debug"

    # Build the application
    - name: Build main project
      run: msbuild GrasshopperBootstrap /p:Configuration="Debug"

    - name: Test2
      run: ls GrasshopperBootstrap\

    # Restore the tests
    - name: Restore tests project
      run: msbuild GrasshopperBootstrap.Tests /t:Restore /p:Configuration="Debug"

    # Build the tests
    - name: Build main project
      run: msbuild GrasshopperBootstrap.Tests /p:Configuration="Debug"

    - name: Test2
      run: ls GrasshopperBootstrap.Tests\

    # Required to add VSTest to path (instead of adding mstest to path)
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v4

    # Run the actual tests
    - name: VSTest
      run: vstest.console GrasshopperBootstrap.Tests\bin\Debug\GrasshopperBootstrap.Tests.dll
